server:
  port: 8765

spring:
  application:
    name: base-admin
  boot:
    admin:
      discovery:
        ignored-services: gateway-service
      ui:
        #brand: MECH-SIMPLE
        title: Administrator
  #security:    #user:      #name: admin
      #password: admin
       
eureka:
  client:
    registryFetchIntervalSeconds: 20
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
       